import { describe, it, expect } from 'vitest';
import { buildEventIcs } from '../../src/lib/ics.mjs';
import { googleCalendarUrl, outlookCalendarUrl, icsPathFor } from '../../src/lib/calendar-links.mjs';
import { eventGraph } from '../../src/lib/structured-data.mjs';

// Pins backwards compatibility with next-events.generated.json entries
// written before this feature: { title, url, date } only, no `end` or
// `location`. The file is gitignored and regenerated by
// scripts/fetch-next-events.mjs, so a dev on an old copy (or a build that
// ran before this change landed) must not crash — every consumer added by
// this feature has to treat both fields as genuinely optional.

const OLD_SHAPE_EVENT = {
	title: 'Monthly meetup',
	url: 'https://www.meetup.com/dotnetnotts/events/123456/',
	date: '2026-09-28T18:00:00.000Z',
};

describe('an event with no end or location (the pre-calendar-export shape)', () => {
	it('still produces a valid ICS file, falling back to the default duration and no LOCATION', () => {
		const ics = buildEventIcs(
			{ slug: 'dot-net-notts', groupName: '.NET Notts', ...OLD_SHAPE_EVENT },
			{ now: new Date('2026-09-01T00:00:00.000Z') },
		);
		expect(ics).toContain('BEGIN:VEVENT');
		expect(ics).toContain('DTSTART:20260928T180000Z');
		expect(ics).toContain('DTEND:20260928T200000Z'); // date + 120 minutes
		expect(ics).not.toContain('LOCATION');
	});

	it('still produces valid calendar links, with no location param', () => {
		const google = new URL(googleCalendarUrl(OLD_SHAPE_EVENT));
		expect(google.searchParams.has('location')).toBe(false);
		expect(google.searchParams.get('dates')).toBe(
			'20260928T180000Z/20260928T200000Z',
		);

		const outlook = new URL(outlookCalendarUrl(OLD_SHAPE_EVENT));
		expect(outlook.searchParams.has('location')).toBe(false);

		expect(icsPathFor('dot-net-notts', OLD_SHAPE_EVENT)).toBe(
			'/calendar/dot-net-notts-20260928T180000Z.ics',
		);
	});

	it('still produces a valid structured-data graph, with no endDate/location on the node', () => {
		const graph = eventGraph(
			[
				{
					id: 'dot-net-notts',
					data: {
						name: '.NET Notts',
						url: 'https://www.meetup.com/dotnetnotts/',
						summary: 'A group.',
					},
				},
			],
			{ 'dot-net-notts': [OLD_SHAPE_EVENT] },
		);
		const [event] = (graph!['@graph'] as any[]).filter(
			(n) => n['@type'] === 'Event',
		);
		expect(event.name).toBe('Monthly meetup');
		expect('endDate' in event).toBe(false);
		expect('location' in event).toBe(false);
		expect(event.eventAttendanceMode).toBe(
			'https://schema.org/OfflineEventAttendanceMode',
		);
	});
});
